"""
---------------------------------------------------
Author  : Roxane Boyer
Purpose : Calculate coverage statistic aggregated
          per gene 
---------------------------------------------------
"""

# -------- Imports -------- #
import argparse
import traceback
from csv import reader

# -------- Classes -------- #
class Bedcov_hist:
    def __init__(self,depth,nbOcc,pctQuery):
        self.depth = depth
        self.nbOcc = nbOcc
        self.pctQuery = pctQuery

    def __str__(self):
        s = str(self.depth) + " " +  str(self.nbOcc) + " " +  str(self.pctQuery)
        return s

class Gene_cov_info:
    def __init__(self,name,querySize):
        self.name = name
        self.querySize = querySize
        self.listRecords = []

    def __str__(self):
        s = "Gene name : " + str(self.name) +\
            "\nSize of match : " + str(self.querySize) +\
            "\nNb records : " + str(len(self.listRecords))
        return s

    def add_record(self,record):
        self.listRecords.append(record)

    def show_records(self):
        s = ""
        for x in range(len(self.listRecords)):
            s += str(self.listRecords[x]) + "\n"
        return s

def get_arguments():
	"""Parsing the arguments"""
	parser = argparse.ArgumentParser(description="",
                                     usage='''
______________________________________________________________________
A tool to calculate coverage statistic per gene. Input is a bedcov file
generated by betools coverage with the -hist option.
______________________________________________________________________
Generic command: python3 cov_per_gene.py -i [input_bedcov] -o [output_csv]

Mandatory arguments:
    -i   The input file generated by bedtools coverage -hist
    -o   The output file in csv format, each field seperated by a coma
        
Output:
    GeneID,MeanCoverage,MedianCoverage,PCTCoverageMin30X

______________________________________________________________________
''')
	parser.add_argument("-i", "--input", help="The input file generated by bedtools coverage -hist", required=True)
	parser.add_argument("-o", "--output", help="The output file in csv format, each field seperated by a coma", required=True)
	return (parser.parse_args())

def read_bedcov(input):
    genes_info = {}
    try:
        with open(input, 'r') as f:
            csv_reader = reader(f, delimiter='\t')
            for row in csv_reader:
                c_gene_name = row[3]
                c_depth = row[8]
                c_nbocc = row[9]
                c_querysize = row[10]
                c_pctquery = row[11]
                c_record = Bedcov_hist(c_depth,c_nbocc,c_pctquery)
                c_gene_cov_info = Gene_cov_info(c_gene_name,c_querysize)
                if not c_gene_name in genes_info:
                    genes_info[c_gene_name] = c_gene_cov_info
                genes_info[c_gene_name].add_record(c_record)
    except Exception as e :
        print('Uh oh, something went wrong there :(. More details below')
        traceback.print_exc()
        raise
    finally:
        f.close()
        return genes_info

test_file = "/Users/roxaneboyer/Bioinformatic/data/vUMC/nice_otter/NA12878_ERATPLUS_10GB.refseq.bedcov.test"
dict = read_bedcov(test_file)
print(dict["DDX11L1:NR_046018.2"])
print(dict["DDX11L1:NR_046018.2"].show_records())
